<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MedallionShell" Version="1.6.2" />
      <PackageReference Include="Mis.Common.Libraries" Version="1.39.0" />
      <PackageReference Include="MIS3.Trucks.Common" Version="0.18.0" />
      <PackageReference Include="Mis3.Trucks.Transport.De.Be.Api" Version="0.64.0" />
    </ItemGroup>

</Project>
